### ISSUE TITLE
Fazer Barra de vida genérica

### ISSUE THREAD

**Issue by Muzamba** [Muzamba/PI-2020-2#14]
# Barra de vida genérica
- Pensei em fazer algo desse estilo
![image](https://user-images.githubusercontent.com/43461390/94490406-975f0b80-01bc-11eb-8ede-375018570203.png)
- Pra ficar genérico basta fazer isso com branco preto e tons de cinza e aplicar a cor pela unity
- Fazer as fotinhas separadas

**Comment by AntiSoraX** [comment]
to fazendo galera, gabrieu ta na area

**Comment by AntiSoraX** [comment]
deixa cmg
